### PR TITLE
Things

### PR DESCRIPTION
**Pull request by webdev03**
image

### CODE REVIEW

**Comment by webdev03** [comment]
NO!

**Comment by ILOVETOMAKESTUFF** [comment]
Oh, sorry LOL. I didn't now what that would do, I thought it would let me view the files (cause I forgot that you could see that in the "Files Changed") 🙄

**Comment by webdev03** [comment]
It's ok! Sorry for being all caps. I was scared you would press the merge button lol

**Comment by webdev03** [comment]
Should I organise the css more or just remove the comments? Will they even help?

**Comment by ILOVETOMAKESTUFF** [comment]
I don't mind the comments. I feel like if there is a "Periscope" button, then that would replace the "Home" button. Maybe we should remove it?

**Comment by ILOVETOMAKESTUFF** [comment]
I don't mind the comments. I feel like if there is a "Periscope" button, then that would replace the "Home" button. Maybe we should remove it?

**Comment by webdev03** [comment]
Yeah, removing the home button would work.

**Comment by ILOVETOMAKESTUFF** [comment]
Oh, and the periscope-search button should be a link to the `index.html` file

**Comment by webdev03** [comment]
Done

**Comment by ILOVETOMAKESTUFF** [comment]
Should I merge?

**Comment by webdev03** [comment]
I have no idea how we will do the API...

**Pull request merged**
